{
 "title": "Rust For Java Developers Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "rust-app,springboot-webflux-app,springboot-webflux-native-app,springboot-mvc-app,springboot-mvc-native-app"
   },
   { "name": "testid", "query": { "query": "label_values(testid)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests infos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(target) (k6_http_reqs_total{scenario=\"benchmark\", testid=~\"$testid\"})",
     "legendFormat": "{{target}} total requets"
    },
    {
     "expr": "100 * (\r\n  (\r\n    sum by(target) (k6_http_reqs_total{scenario=\"benchmark\", expected_response=\"false\", testid=~\"$testid\"})\r\n    or\r\n    sum by(target) (k6_http_reqs_total{scenario=\"benchmark\", testid=~\"$testid\"}) * 0\r\n  )\r\n  /\r\n  sum by(target) (k6_http_reqs_total{scenario=\"benchmark\", testid=~\"$testid\"})\r\n)",
     "legendFormat": "{{target}} failure rate"
    }
   ]
  },
  {
   "title": "Requests infos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(target) (rate(k6_http_reqs_total{scenario=\"benchmark\", testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent{container_name=~\"$app\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(docker_container_mem_usage{container_name=~\"$app\"}[$__range:]) > 0",
     "legendFormat": "{{container_name}} minimum"
    },
    {
     "expr": "max_over_time(docker_container_mem_usage{container_name=~\"$app\"}[$__range])",
     "legendFormat": "{{container_name}} maximum"
    },
    {
     "expr": "avg_over_time(docker_container_mem_usage{container_name=~\"$app\"}[$__range])",
     "legendFormat": "{{container_name}} average"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_mem_usage{container_name=~\"$app\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Concurrent user",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by(target) (k6_vus{testid=~\"$testid\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Current CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{container_name=~\"$app\"}",
     "legendFormat": "{{container_name}} "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(docker_container_cpu_usage_percent{container_name=~\"$app\"}[$__range:])",
     "legendFormat": "{{container_name}} minimum"
    },
    {
     "expr": "max_over_time(docker_container_cpu_usage_percent{container_name=~\"$app\"}[$__range])",
     "legendFormat": "{{container_name}} maximum"
    },
    {
     "expr": "avg_over_time(docker_container_cpu_usage_percent{container_name=~\"$app\"}[$__range])",
     "legendFormat": "{{container_name}} average"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{container_name=~\"$app\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Minimal response time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "k6_ep_get_min{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} GET /{id}"
    },
    {
     "expr": "k6_ep_list_min{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} GET"
    },
    {
     "expr": "k6_ep_stats_min{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} GET /stats"
    },
    {
     "expr": "k6_ep_create_min{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} POST"
    },
    {
     "expr": "k6_ep_update_min{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} PATCH"
    }
   ]
  },
  {
   "title": "p99 response time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "k6_ep_get_p99{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} GET /{id}"
    },
    {
     "expr": "k6_ep_list_p99{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} GET"
    },
    {
     "expr": "k6_ep_stats_p99{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} GET /stats"
    },
    {
     "expr": "k6_ep_create_p99{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} POST"
    },
    {
     "expr": "k6_ep_update_p99{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} PATCH"
    }
   ]
  },
  {
   "title": "Avegare response time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_ep_get_avg{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} GET /{id}"
    },
    {
     "expr": "k6_ep_list_avg{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} GET"
    },
    {
     "expr": "k6_ep_stats_avg{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} GET /stats"
    },
    {
     "expr": "k6_ep_create_avg{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} POST"
    },
    {
     "expr": "k6_ep_update_avg{scenario=\"benchmark\", testid=~\"$testid\"}",
     "legendFormat": "{{target}} PATCH"
    }
   ]
  }
 ]
}